properties:
  consul:
    require_ssl: false
    agent:
      servers:
        lan:
          - 5.5.5.5
  loggregator:
    etcd:
      machines:
        - etcd1.foo.bar
  loggregator_endpoint:
    shared_secret: secret123
  diego:
    rep:
      bbs:
        require_ssl: false

jobs:
  - properties:
      diego:
        rep:
          zone:
            zone1
