properties:
  consul:
    agent:
      servers:
        lan:
          - consul1.foo.bar
  etcd:
    machines:
      - etcd1.foo.bar
  loggregator_endpoint:
    shared_secret: secret123
  diego:
    etcd:
      ca_cert: ETCD_CA_CERT
      client_cert: ETCD_CLIENT_CERT
      client_key: ETCD_CLIENT_KEY

jobs:
  - properties:
      diego:
        rep:
          zone:
            zone1
