properties:
  consul:
    ca_cert: CONSUL_CA_CERT
    agent_cert: CONSUL_AGENT_CERT
    agent_key: CONSUL_AGENT_KEY
    encrypt_keys:
      - CONSUL_ENCRYPT
    agent:
      servers:
        lan:
          - consul1.foo.bar
  etcd:
    machines:
      - etcd1.foo.bar
  loggregator_endpoint:
    shared_secret: secret123
  diego:
    etcd:

jobs:
  - properties:
      diego:
        rep:
          zone:
            zone1
